'use client';

import HomePage from '@/components/Home/page';
import Navigation from '@/components/Navigation/page';
import { Inter } from 'next/font/google';
import './globals.css';
import { Footer } from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation></Navigation>
        {children}
        <HomePage></HomePage>
        <Footer></Footer>
      </body>
    </html>
  );
}
